on:
  push:
    paths:
      - Makefile
      - '*.json'
      - '*.hbs'
      - '*.ts'

jobs:
  build:
    strategy:
      matrix: 
        deno-version: [ v1.x.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno@${{ matrix.deno-version }}-${{ hashFiles('**/deps.ts') }}
      - name: Build files
        run: make clean build
      - name: Upload changes
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add --all
          git commit -am "build: Updated README"
          git push